### ISSUE TITLE
Tree builder/parser error parsing ellipsis

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#153]
This ellipsis (`...`) in line: `array_merge(...array_map('class_uses', array_values($types)))` appears to be being interpreted as a property declaration which causes some `[TypeError: Cannot read property '3' of undefined]` errors later down the line.

```php
public static function getClassTree(\ReflectionClass $class)
{
	$addTraits = function ($types) use (& $addTraits) {
		if ($traits = array_merge(...array_map('class_uses', array_values($types)))) {
			$types += $traits + $addTraits($traits);
		}
		return $types;
	};
	$class = $class->getName();
	return array_values($addTraits([$class] + class_parents($class) + class_implements($class)));
}
```

_Framework: **Nette 2.4**_
File: `Nette/DI/PhpReflection.php`

**Comment by ichiriac** [comment]
Hi,

I've added a new flag -s for the suppressErrors option on the tests script. 

If you run tests over your code with `php-parser\bin>node test.js -f ../test/parser/class.parser -v -s` you will see that your class will pass, but will be bad-formed.

If you run tests over your code with `php-parser\bin>node test.js -f ../test/parser/class.parser -v` you will see that reason of faillure :

```
Line 10 : T_ELLIPSIS @at Object.read_function_argument_list (C:\Oracle\ich
php-parser\src\parser\function.js:141:24)
Error: Parse Error : unexpected T_ELLIPSIS, expecting 'EXPR' at line 10`
```

The reason can be found just before the error : function.js starting at line 141 (it's the last token consummation).

As you can see it enters into the read_argument_list function, that seems to handle T_ELLIPSIS : https://github.com/glayzzle/php-parser/blob/master/src/parser/function.js#L159

The problem is that i check the current token, but instead consuming it to go at the next token and parse it as an expression, I just parse the T_ELLIPSIS as an expression.
