### ISSUE TITLE
Update php-parser to use latest version (2.0.0)

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#183]

**Comment by ichiriac** [comment]
Hi @nevadascout,

For your information, I've fixed last bugs and I will release the code under 0.1.2 this weekend. Actually tests pass over these frameworks : https://github.com/glayzzle/php-parser/blob/master/.gitmodules

Tell me if you need to cover other frameworks, or I've missed a bug.

**Comment by nevadascout** [comment]
Thanks @ichiriac 😄

**Comment by ichiriac** [comment]
Warning on backward compatibility, 

The next implementation will support comments as you can see here https://github.com/glayzzle/php-parser/commit/54a4521df433c3c6ce9eb284f526df502c21a5cc - So if you enable them with `parser.extractDoc = true` class nodes will be prefixed with doc or comments nodes as you can see here https://github.com/glayzzle/php-parser/blob/master/test/functional/commentTests.js

By default they are disabled, so the behavior should be the same as before.

It's missing tests for publishing the new version, need about another week to fully implement nodes positions and comments.

There is some issues with AST (they were here from always) as you can see here (https://travis-ci.org/glayzzle/php-parser/builds/179250360) - so need more fixes. 

I wish the next release to be solid rock with much less bugs so I can start to work on my other glayzzle project - I'll notify here when the release is published.

**Comment by ichiriac** [comment]
FYI - 0.1.2 released :tada: - many AST fixes done, now parsing AST correctly from any framework (including php7)

**Comment by ichiriac** [comment]
Hi @nevadascout,

I'm actually preparing a new library based on php-parser : https://github.com/glayzzle/php-reflection and I plan to move some code there.

The idea behind this library is to enable code reflection like an in-memory database - far more easy to use than the plain array version.

What it will do :
 - can add files to be analyzed
 - can lookup functions, classes, namespace, traits...
 - can handle references (like where a class is defined, where is instanciated, where is used as declaration)
 - can handle files refreshing (with a datetime flag to check if file need refresh)
 - can handle scopes (like in file.php at offset X it will return an object with the current namespace, current class, function, list of variables)
 - can handle caching (gets/sets a json serializable object from repository state)

Moved code :

 - the gracefull mode : it's not necessary to be defined in the AST parser, it's more a specific behaviour
 - the comments : I will implement a docBlock parser dirrectly inside this project (php-parser will only return comments with comments sources

I've made the plain array version in order to parse as fast as possible with the least memory usage (for writing a transcripter) but for your project (and maybe others) is not enough easy to use directly.

Stay tuned :smile:

**Comment by nevadascout** [comment]
Sounds great! I look forward to seeing it!

**Comment by ichiriac** [comment]
@nevadascout 

It starts to work but I've made a major release on php-parser(0.1.3) for this (a major bug on static instanciation - now it's using real prototyped instances) and remains commits. 

I will finish all library before releasing it.

You can take a look at the API documentation [here](https://github.com/glayzzle/php-reflection/tree/master/docs) - and you can try it from `test/index.js`

The hard part is done, now remains the fun part of defining nodes :smile:

**Comment by ichiriac** [comment]
Hi @nevadascout,

I would like to chat with you about migrating crane. The php-reflection is functionnal and runs well, could correct major party of bugs here.

Could you please tell me how I can help.

**Comment by nevadascout** [comment]
Hey @ichiriac that sounds great!

I've been pretty busy lately, but lets talk at some point this week about getting this done! Is Gitter the best place to talk?

**Comment by ichiriac** [comment]
It's fine for me, I've already found your profile & tried to contact you by gitter :smile: - I'm online each night, so we can chat when you want.

See u soon, Ioan

**Comment by nevadascout** [comment]
Released in v0.3.0
