### ISSUE TITLE
Bug report link doesn't work on xubuntu

### ISSUE THREAD

**Issue by qcol** [HvyIndustries/crane#189]
I found bug... nothing happens if I click on the "Found bug?" text :)

Xubuntu Crane v0.2.2, Code Version 1.7.2

![zaznaczenie_172](https://cloud.githubusercontent.com/assets/358993/20621904/c15db4a4-b300-11e6-971b-d6785ff4af6c.png)

**Comment by ichiriac** [comment]
:smile:

**Comment by ichiriac** [comment]
It's a platform issue. We could use https://github.com/sindresorhus/opn in order to handle any edge case.

In order to be able to track user plateform, it would be great to define a default text with following informations :

* The crane version
* The OS/Plateform
* VSCode version
* Last error / with stack (we would need to track and save into a variable the last error raised)

We can use github querystring parameters to define default values : https://github.com/HvyIndustries/crane/issues/new?body=Hello%20`world`

Here a list of supported parameters : https://developer.github.com/v3/issues/#create-an-issue

@nevadascout do you agree, and do you see any other helpfull information that could be provided ?

**Comment by nevadascout** [comment]
Fixed in v0.3.2
