### ISSUE TITLE
Add namespace to class insert text when there is no use statement for it

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#224]
When instantiating a class with `new` or direct access, we should include the FQN if there is no `use` statement for it.

```php
use Namespace\MyClass;

$foo = new MyClass();
//         ^ namespace is not added because of use statement

$bar = new Namespace\OtherClass();
//         ^ namespace is added because of there is no use statement
```

This needs to apply to:
- [x] Class instantiation: `new Class()`
- [x] Static class access `Class::`

**Comment by ichiriac** [comment]
Just a TIP : PHP7 introduce the namespace keyword into the names part (see the 2nd point https://github.com/php/php-langspec/blob/master/spec/18-namespaces.md#name-lookup) 

For example :

```php
<?php
namespace foo;
  use bar\FooBar;
  $a = new FooBar(); // resolved as bar\FooBar
  $b = new namespace\FooBar(); // resolved as foo\FooBar
```

What about doing like eclipse and append the use statement automatically ? A good practice would be to have all use Statements into the file headers in order to simplify refactoring (replace just the use statement in order to replace a class usage)

When instanciating a new class, the system could automatically append it on current namespace section (if any) or in the top of the file, and strip its namespace prefix (that's the behavior of Eclipse in Java).

**Comment by nevadascout** [comment]
Core functionality added in v0.3.1

New task created for PHP7 `namespace` keyword in `use` statements: #243
