### ISSUE TITLE
Request textDocument/completion failed

### ISSUE THREAD

**Issue by FlyProg** [HvyIndustries/crane#257]
After update Crane for the version 0.3.1 I receive allways this mensage:

_[Error - 15:56:25] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'classes' of undefined
  Code: -32603_

**Comment by ichiriac** [comment]
Hi @FlyProg,

You have the same error message as https://github.com/HvyIndustries/crane/issues/244 issue. Does your workspace located into an network drive ?

**Comment by FlyProg** [comment]
Hi ichiriac
No, my workspace is into local machine.

**Comment by ichiriac** [comment]
In order to get more information, could follow steps from this comment https://github.com/HvyIndustries/crane/issues/244#issuecomment-285193107 and send us more informations about the error. We need an error stack in order to locate the error and try to understand what happened.

Also it could help us to know your vscode versions taken from the about box.

**Comment by FlyProg** [comment]
Now with version 0.3.2 the mensages that we receive are:

_[Error - 17:08:22] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'namespaceUsings' of null
  Code: -32603 
[Error - 17:36:36] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'classes' of undefined
  Code: -32603_

**Comment by ichiriac** [comment]
I can also reproduce it but don't know yet why.

The bug is raised from `server/src/suggestionBuilder.ts` line 624, this.currentFileNode is null.

currentFileNode  is null because he current file can not be parsed. The file is not parsed because the `this` scope is lost from this promise :

![image](https://cloud.githubusercontent.com/assets/173203/24075583/8c8b93aa-0c1e-11e7-831f-6b41e4656985.png)

**Comment by ichiriac** [comment]
As @CarlosAzocar pointed out, we may also have problems with decoding pathUri, same error results.

Actualy the `Files.getPathFromUri` and `getUriFromPath` uses replace to handle `%3A` -> `:`. A more generic way could be to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI

**Comment by nevadascout** [comment]
Update URI encode/decode in v0.3.4. If the problem persists, please let us know @FlyProg!
