### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by jsparrow58** [HvyIndustries/crane#27]
`// Whether php validation is enabled or not.`
`"php.validate.enable": true,`
`// Points to the php executable.`
`"php.validate.executablePath":"D:/wamp/bin/php/php5.5.12/php.exe",`
`// Whether the linter is run on save or on type.`
`"php.validate.run": "onType"`

i set the value,but it still doesn't work.
why?

**Comment by oxrc** [comment]
Hey there,

I have the same problem. I run it on windows 10, with php linter set on type, just like in the comment above.

I does not work at all - variables are still not shown, even though the file is marked as PHP. I have other extensions enabled - may they interfere in some way?

**Comment by nevadascout** [comment]
Hi guys, sorry you're having some problems with the extension :-1:

Some things to note:
1. It only builds up suggestions when you save the file
2. It only builds suggestions if there aren't any syntax errors in the file

**To get it working, check the linter isn't reporting any syntax errors for the file you're editing and save it. You should then get some suggestions.**

I know this is annoying *(and the inconsistent suggestion behaviour irritates me no end)*, but at the moment I'm limited by the PHP parser that I'm using.

It's on my list to get it working much, much more reliably very soon - hopefully within a week or so.

Also, @oxrc - having other extensions installed shouldn't cause any problems.

**Comment by hworld** [comment]
Was curious about this. Basically, while typing it always triggers a syntax error because there is no `;` at end of line. Does that mean that it will never trigger completions correctly? It's been very random as to when it actually suggests completions.

Really looking forward to the development of this extension, btw! I've been wanting this for so long and it seems like you've got a great base going. :+1:

**Comment by nevadascout** [comment]
I've added an event handler so that when you type a `;`, `)` or `}` it tries to rebuild a list of suggestions, as I'm hoping the syntax will be valid at that point!

But the most reliable way to build suggestions is to save the file without any syntax errors. The suggestion list is cached, so if you introduce a syntax error after doing this the _(potentially)_ outdated suggestions will still be in the list.

It is very random, and it's pretty annoying to sometimes get suggestions and not. The main issue is with the php parser that I'm using - if it encounters a syntax error it throws an exception, throwing away the syntax tree that it has built up to that point.

I'll have to add an option to stop it throwing exceptions and just return what it's go so far, and send them a pull request.

Ideally I'd fork the project and make the parser ignore any lines that have syntax errors... That would help a **lot** for this use case.

Thanks for the kind words, I really want to make this extension as good as possible - to rival PHPStorm and other full editors :)

**Comment by hworld** [comment]
Thanks for the info! I'll be following along as the project matures. Got it installed. =]

**Comment by ILILE** [comment]
I hope you get issue #7 solved soon, I'd love to use this extension but it doesn't work at all for me, and I guess that's the reason.

**Comment by nevadascout** [comment]
@ILILE support for namespaces is top of my list for the next release!

**Comment by nevadascout** [comment]
@ILILE @hworld @jsparrow58 @oxrc Just released version 0.1.6 which adds support for namespaces and should hopefully make the code suggestions much more reliable. :+1: 

More info here: https://github.com/HvyIndustries/crane/releases/tag/0.1.6

**Comment by sirio3mil** [comment]
There is a log when I can see fails on this extension? I have a big project and it fail.

**Comment by nevadascout** [comment]
Not currently, but I'll add a debug option for the next release.

**Comment by nevadascout** [comment]
These issues should be resolved in the 0.2 release coming out shortly.

Feel free to open a new issue if you're still having issues after the release.
