### ISSUE TITLE
Can't type dollar symbol $ when on french keyboard layout

### ISSUE THREAD

**Issue by foxyantho** [HvyIndustries/crane#31]
Hello,

Currently running on Ubuntu 14.04 , with keyboard layout set on "Français" ( French AZERTY ).

Whenever I press the dollar-symbol `$` key, it's a semicolon `;` which appear instead.

It's the only key that cause trouble. Moreover this bug only occur on PHP files, I can properly type the dollar `$` anywhere else.

**Comment by netvision73** [comment]
Hello,

Same for me here. I uninstalled it to make `$` work again.

**Comment by bchanudet** [comment]
Hi !

Facing the same problem here, I did some investigation.
The bug comes most likely from using keybindings to detect user input in the editor window.

On a French AZERTY keyboard, the `$` key triggers the `VK_OEM_1` virtual key event, that has `;` as a representation in vscode according to the [doc](https://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts). 

Looking at `package.json` we will also have a problem with the `}` key, that is translated here by "ctrl+shit+=" and the `)` key (translated as `[`). Yeah we do a lot of altGr+ combinations when we code here in France :)

I looked at it more again, and found that this [vim-extension for vscode](https://github.com/alexandrudima/vscode-vim) handles input differently, by overloading the default `type` event, doing some things on it, and then giving the hand back to the default vscode `default:type` event

I did some modifications to the client based on this idea and I was able to type again my precious characters with Crane installed. I can do a PR if you want to see it. It's basically removing all keybindings, register `handleKeyPress()` for the `type` event, looking for the characters `$ } ; )` directly in the function (and calling `buildObjectTreeForDocument()` if found), then calling `commands.executeCommand('default:type',...)` to insert the character in the current text editor.

Hope I helped,

Cheers !

**Comment by nevadascout** [comment]
Ooh, this is a good point!

@bchanudet Yes, please submit a PR! I'm keen to get this working properly for languages other than English :)

**Comment by nevadascout** [comment]
For now, I'll disable this "feature" and will fix it in the next version after this one (will be 0.1.7).

**Comment by nevadascout** [comment]
After reviewing the latest version of the parser, this feature is no longer needed and the broken functionality has been removed.
